### ISSUE TITLE
Set up analytics

### ISSUE THREAD

**Issue by GemCopeland** [commonknowledge/crimes-of-solidarity#23]
From Lucy:
> Where can I find the analytics. This will be important for making the case for sustained funding in the future so I need to keep a record of the stats. 

@King-Mob are there analytics set up already? If not, @janbaykara could probably do that as he quite enjoys it I think!

- [x] Set up Fathom @janbaykara
- [ ] <s>Backport logs from Vercel @conatus</s>

**Comment by Mayblin** [comment]
Just checking up on this. Where can I find the analytics? Thanks!

**Comment by GemCopeland** [comment]
@janbaykara do you think you could set this up this week please?

**Comment by GemCopeland** [comment]
@conatus is going to do this today.

**Comment by conatus** [comment]
Need to replace these lines - https://github.com/commonknowledge/crimes-of-solidarity/blob/main/pages/_app.tsx#L20-L26

By the way it won't mis-report Game Worker's Solidarity on the live site. It only records the domains you set up there.

**Comment by conatus** [comment]
I have deployed this. Will check tomorrow that it is deployed.

**Comment by Mayblin** [comment]
Can you please tell me how to access analytics?

**Comment by conatus** [comment]
@Mayblin 

Apologies for the delay in reply. We are using [Fathom](https://usefathom.com/) for Analytics at the moment and need to liase with their team to transfer you the account. Will look back once we know a bit more.

**Comment by Mayblin** [comment]
OK thank you. Will the analytics be visible from when the website was launched? And any idea on the timeline?

**Comment by janbaykara** [comment]
Hi @Mayblin. I've enabled a public dashboard view of the analytics that you and anyone else can access here: https://app.usefathom.com/share/wljdosuv/crimes+of+solidarity+and+humanitarianism This can be shared safely as there is no personal data tracked by Fathom.

**Comment by janbaykara** [comment]
Feel free to reopen this issue if there's anything missing!

**Comment by janbaykara** [comment]
Bit of light documentation. If you want to get a view of a particular time period, for example "last month" or "[all time](https://app.usefathom.com/share/wljdosuv/crimes+of+solidarity+and+humanitarianism?page=1&range=all_time&sort=visitors%3Adesc)", just use the date picker in the top right:

<img width="757" alt="Screenshot 2022-08-04 at 10 54 00" src="https://user-images.githubusercontent.com/237556/182819067-2c3b0f53-18bd-41fa-bfc3-87ef93fdb7a5.png">

**Comment by Mayblin** [comment]
Thank you Jan
_____________
Dr Lucy Mayblin
Senior Lecturer in Sociology

Department of Sociological Studies
University of Sheffield
Sheffield
S10 2TU

Email: ***@***.***
Web: https://lucymayblin.com
Phone: +44 (0)114 2226445
Tweet: @lucymayblin
