### ISSUE TITLE
Text in search box

### ISSUE THREAD

**Issue by Mayblin** [commonknowledge/crimes-of-solidarity#27]
In the general search box, though it's just a free text search of all cases, the grey text in the box says something lie 'search for countries, types etc'. Can this be changes just to 'search' so it is clear to people that they can search the whole site. Someone asked me today if I could add a search function so they could see all the cases involving 'search and rescue' and they hadn't realised they could use that search box to do that.

**Comment by janbaykara** [comment]
That's fixed now @Mayblin :)
